# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ouachita Hills Ministries
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ouachitahills.org" # the base hostname & protocol for your site
repo: ohministries/ohministries.github.io
branch: master
collections:
- news
sass:
  style: compressed